### PR TITLE
MODORDERS-246 - Create a script to generate and load performance test data

### PR DESCRIPTION
**Pull request by khandramai**
JMeter script for reference data loading for orders/order-lines.

### CODE REVIEW

**Comment by khandramai** [comment]
Console running:
Снимок экрана 2019-06-02 в 23 36 20

**Comment by khandramai** [comment]
Console run: 1 thread, 100 records.
Снимок экрана 2019-06-03 в 0 40 28
Снимок экрана 2019-06-03 в 0 40 34

**Comment by khandramai** [comment]
Console run: 2 threads, 100 records. Total: 200 records.
Снимок экрана 2019-06-03 в 0 47 12
Снимок экрана 2019-06-03 в 0 47 23

**Comment by khandramai** [comment]
@craigmcnally, 
could you please provide more details to reproduce problem, i.e I would like to know number of threads and number of records per thread. Did you use default percentage from file percentage.csv?

**Comment by craigmcnally** [comment]
$ cat config.csv 
diku,diku_admin,*****,https,folio-snapshot-okapi.aws.indexdata.com,443,1,20

$ cat percentage.csv 
50,20,30,50,20,30

**Comment by craigmcnally** [comment]
```$ cat jmeter_Orders_DataLoader.jmx.log 
2019-06-03 16:33:59,759 INFO o.a.j.u.JMeterUtils: Setting Locale to en_EN
2019-06-03 16:33:59,811 INFO o.a.j.JMeter: Loading user properties from: /opt/apache-jmeter-5.1.1/bin/user.properties
2019-06-03 16:33:59,813 INFO o.a.j.JMeter: Loading system properties from: /opt/apache-jmeter-5.1.1/bin/system.properties
2019-06-03 16:33:59,814 INFO o.a.j.JMeter: Setting JMeter property: jmeter.saveaveservice.output_format=xml
2019-06-03 16:33:59,826 INFO o.a.j.JMeter: Copyright (c) 1998-2019 The Apache Software Foundation
2019-06-03 16:33:59,826 INFO o.a.j.JMeter: Version 5.1.1 r1855137
2019-06-03 16:33:59,826 INFO o.a.j.JMeter: java.version=1.8.0_171
2019-06-03 16:33:59,826 INFO o.a.j.JMeter: java.vm.name=Java HotSpot(TM) 64-Bit Server VM
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: os.name=Linux
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: os.arch=amd64
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: os.version=4.4.0-145-generic
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: file.encoding=UTF-8
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: java.awt.headless=true
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: Max memory     =1073741824
2019-06-03 16:33:59,827 INFO o.a.j.JMeter: Available Processors =1
2019-06-03 16:33:59,842 INFO o.a.j.JMeter: Default Locale=English (EN)
2019-06-03 16:33:59,843 INFO o.a.j.JMeter: JMeter  Locale=English (EN)
2019-06-03 16:33:59,843 INFO o.a.j.JMeter: JMeterHome=/opt/apache-jmeter-5.1.1
2019-06-03 16:33:59,843 INFO o.a.j.JMeter: user.dir  =/home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader
2019-06-03 16:33:59,843 INFO o.a.j.JMeter: PWD       =/home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader
2019-06-03 16:33:59,844 INFO o.a.j.JMeter: IP: 127.0.1.1 Name: Bruin FullName: Bruin
2019-06-03 16:33:59,852 INFO o.a.j.s.FileServer: Default base='/home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader'
2019-06-03 16:33:59,865 INFO o.a.j.s.FileServer: Set new base='/home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader'
2019-06-03 16:34:00,234 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2019-06-03 16:34:00,274 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2019-06-03 16:34:00,290 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2019-06-03 16:34:00,309 INFO o.a.j.s.SaveService: Loading file: Orders-DataLoader.jmx
2019-06-03 16:34:00,446 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-06-03 16:34:00,446 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-06-03 16:34:00,447 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-06-03 16:34:00,448 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-06-03 16:34:00,448 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2019-06-03 16:34:00,448 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2019-06-03 16:34:00,764 INFO o.a.j.JMeter: Creating summariser <summary>
2019-06-03 16:34:00,788 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-06-03 16:34:00,789 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-06-03 16:34:00,789 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-06-03 16:34:00,816 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2019-06-03 16:34:00,816 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2019-06-03 16:34:02,905 INFO o.a.j.JMeter: Running test (1559579642904)
2019-06-03 16:34:02,913 INFO o.a.j.e.StandardJMeterEngine: Starting setUp thread groups
2019-06-03 16:34:02,914 INFO o.a.j.e.StandardJMeterEngine: Starting setUp ThreadGroup: 1 : Login 
2019-06-03 16:34:02,914 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Login.
2019-06-03 16:34:02,914 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-06-03 16:34:02,914 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=0 delayedStart=false
2019-06-03 16:34:02,931 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-06-03 16:34:02,931 INFO o.a.j.e.StandardJMeterEngine: Waiting for all setup thread groups to exit
2019-06-03 16:34:02,963 INFO o.a.j.t.JMeterThread: Thread started: Login 1-1
2019-06-03 16:34:02,966 INFO o.a.j.s.FileServer: Stored: percentage.csv
2019-06-03 16:34:02,966 INFO o.a.j.s.FileServer: Stored: config.csv
2019-06-03 16:34:03,051 INFO o.a.j.p.h.s.HTTPHCAbstractImpl: Local host = Bruin
2019-06-03 16:34:03,083 INFO o.a.j.p.h.s.HTTPHC4Impl: HTTP request retry count = 0
2019-06-03 16:34:03,091 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2019-06-03 16:34:03,091 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2019-06-03 16:34:03,092 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2019-06-03 16:34:03,092 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2019-06-03 16:34:03,508 INFO o.a.j.p.h.s.h.LazyLayeredConnectionSocketFactory: Setting up HTTPS TrustAll Socket Factory
2019-06-03 16:34:03,526 INFO o.a.j.u.JsseSSLManager: Using default SSL protocol: TLS
2019-06-03 16:34:03,526 INFO o.a.j.u.JsseSSLManager: SSL session context: per-thread
2019-06-03 16:34:04,046 INFO o.a.j.u.SSLManager: JmeterKeyStore Location:  type JKS
2019-06-03 16:34:04,061 INFO o.a.j.u.SSLManager: KeyStore created OK
2019-06-03 16:34:04,061 WARN o.a.j.u.SSLManager: Keystore file not found, loading empty keystore
2019-06-03 16:34:06,040 INFO o.a.j.e.J.JSR223 PostProcessor - Save token: Successfully logged in...
2019-06-03 16:34:06,096 INFO o.a.j.e.J.JSR223 PostProcessor - Save token: x-okapi-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaWt1X2FkbWluIiwidXNlcl9pZCI6ImZmMDYxZDAwLTVhZWUtNTA3ZC1hYzg4LWVhOWM2YWI3YjU2NSIsImNhY2hlX2tleSI6IjljZTkyZGRjLWQ0NjUtNGVkMS1iNWRmLTFhYzYxODVlZDc4YSIsImlhdCI6MTU1OTU3OTY0NiwidGVuYW50IjoiZGlrdSJ9.Z6FxahKzp3BNTkAGm5w4pKS3dQyT3Lv6-ed2ctxpB9I
2019-06-03 16:34:06,209 INFO o.a.j.t.JMeterThread: Thread is done: Login 1-1
2019-06-03 16:34:06,210 INFO o.a.j.t.JMeterThread: Thread finished: Login 1-1
2019-06-03 16:34:06,212 INFO o.a.j.e.StandardJMeterEngine: All Setup Threads have ended
2019-06-03 16:34:06,364 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : SetUp
2019-06-03 16:34:06,364 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group SetUp.
2019-06-03 16:34:06,364 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-06-03 16:34:06,364 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=0 delayedStart=false
2019-06-03 16:34:06,367 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-06-03 16:34:06,367 INFO o.a.j.e.StandardJMeterEngine: Waiting for thread group: SetUp to finish before starting next group
2019-06-03 16:34:06,368 INFO o.a.j.t.JMeterThread: Thread started: SetUp 1-1
2019-06-03 16:34:07,915 INFO o.a.j.e.J.JSR223 PostProcessor - Initial state: Initial number of orders: 14
2019-06-03 16:34:08,044 INFO o.a.j.e.J.JSR223 PostProcessor - Initial state: Initial number of order-lines: 16
2019-06-03 16:34:08,045 INFO o.a.j.t.JMeterThread: Thread is done: SetUp 1-1
2019-06-03 16:34:08,045 INFO o.a.j.t.JMeterThread: Thread finished: SetUp 1-1
2019-06-03 16:34:08,049 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 2 : DataLoader
2019-06-03 16:34:08,060 INFO o.a.j.f.FileWrapper: Attaching /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,064 INFO o.a.j.f.FileWrapper: Opening /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv as /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,065 INFO o.a.j.s.FileServer: Stored: /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,065 INFO o.a.j.f.FileWrapper: Saved /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv as /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv delimiter=<,>
2019-06-03 16:34:08,069 INFO o.a.j.f.FileWrapper: Stored /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv as /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,070 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group DataLoader.
2019-06-03 16:34:08,071 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-06-03 16:34:08,071 INFO o.a.j.t.ThreadGroup: Starting thread group... number=2 threads=1 ramp-up=0 delayedStart=false
2019-06-03 16:34:08,089 INFO o.a.j.t.ThreadGroup: Started thread group number 2
2019-06-03 16:34:08,089 INFO o.a.j.e.StandardJMeterEngine: Waiting for thread group: DataLoader to finish before starting next group
2019-06-03 16:34:08,104 INFO o.a.j.t.JMeterThread: Thread started: DataLoader 2-1
2019-06-03 16:34:08,107 INFO o.a.j.f.FileWrapper: Attaching /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,107 INFO o.a.j.f.FileWrapper: Opening /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv as /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,107 INFO o.a.j.f.FileWrapper: Stored /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv as /home/cmcnally/git/folio-perf-test/Folio-Test-Plans/mod-orders/data-loader/config.csv
2019-06-03 16:34:08,741 INFO o.a.j.e.J.JSR223 PostProcessor - Save vendorId: Data loading will be processed for vendorId: 
2019-06-03 16:34:08,950 INFO o.a.j.e.J.JSR223 PostProcessor - Save instanceId, instanceTitle: Data loading will be processed for instanceId: a89eccf0-57a6-495e-898d-32b9b2210f2f
2019-06-03 16:34:25,408 INFO o.a.j.t.JMeterThread: Thread is done: DataLoader 2-1
2019-06-03 16:34:25,409 INFO o.a.j.t.JMeterThread: Thread finished: DataLoader 2-1
2019-06-03 16:34:25,410 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2019-06-03 16:34:25,410 INFO o.a.j.e.StandardJMeterEngine: Starting tearDown thread groups
2019-06-03 16:34:25,410 INFO o.a.j.e.StandardJMeterEngine: Starting tearDown ThreadGroup: 1 : TearDown
2019-06-03 16:34:25,410 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group TearDown.
2019-06-03 16:34:25,411 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-06-03 16:34:25,411 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=0 delayedStart=false
2019-06-03 16:34:25,415 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-06-03 16:34:25,417 INFO o.a.j.t.JMeterThread: Thread started: TearDown 1-1
2019-06-03 16:34:26,044 INFO o.a.j.e.J.JSR223 PostProcessor - Final state: Final number of orders: 14
2019-06-03 16:34:26,131 INFO o.a.j.e.J.JSR223 PostProcessor - Final state: Final number of order-lines: 16
2019-06-03 16:34:26,131 INFO o.a.j.t.JMeterThread: Thread is done: TearDown 1-1
2019-06-03 16:34:26,131 INFO o.a.j.t.JMeterThread: Thread finished: TearDown 1-1
2019-06-03 16:34:26,135 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2019-06-03 16:34:26,135 INFO o.a.j.s.FileServer: Close: config.csv
2019-06-03 16:34:26,136 INFO o.a.j.s.FileServer: Close: percentage.csv
2019-06-03 16:34:26,143 INFO o.a.j.r.Summariser: summary =     67 in 00:00:23 =    2.9/s Avg:   312 Min:    58 Max:  3599 Err:    61 (91.04%)
```

**Comment by khandramai** [comment]
Yes, thanks. You confirmed my hunch by your logs. Line `2019-06-03 16:34:08,741` doesn't contain vendorId so it wasn't retrieved and as a result flow failed. I have to continuing problem investigation.

**Comment by khandramai** [comment]
@craigmcnally ,
the problem was in usage of deprecated vendors API. This changed on organizations API and verified on folio-snapshot-okapi.aws.indexdata.com:
Снимок экрана 2019-06-04 в 0 12 29

**Pull request merged**
