### PR TITLE
Initial checkin

### PR DESCRIPTION
**Pull request by hjiebsco**

### CODE REVIEW

**Comment by wafschneider** [comment]
This is super clever and efficient. I'd love to see @hjiebsco's work as Ansible roles in folio-ansible, but I'm not sure it's worth the effort to move it over when this works.

I've asked @dcrossleyau to take a look at the branch to make sure the initial commit ticks all the boxes for public repositories. @funkymalc -- can you look at the repo configuration so that we don't have failed checks? (Seems like the branch and pr-merge checks might not be relevant).

It appears that this generates only a backend, no frontend, correct? So that might be something to add later (but doesn't prevent us from making the merge).

I am concerned about the data population step. I wonder if here there is a role for using or adapting the roles in folio-ansible? I don't want to add a dependency if one isn't needed. I wonder if using GitHub repos with a similar structure that can be versioned and downloaded as tarballs might be a better approach (rather than using S3). I also wonder about using the APIs where possible, rather than doing database inserts (although performance for that is of course much slower).

Other thoughts? Once @dcrossleyau and @funkymalc give this the once-over, I think we should merge and start work on adding a frontend build and on refining data population.

**Comment by hjiebsco** [comment]
@wafschneider, thank you very much for the nice comments. 1) I did not use Ansible simply because we do not have much experience with it. Jenkins and AWS do the CICD in our team 2) Only backend is generated because JMeter test is at API level 3) db-populate is what we use here for now. With the newly introduced RMB admin API to drop/create indexes, I am thinking to leverage that once modules upgrade to the new RMB. By the way, we store large dataset in s3 mostly for cost and performance reasons.
@dcrossleyau, thank you very much to keep things neat. I appreciate that.

**Comment by dcrossleyau** [comment]
Thanks for saying so. There was not much to do there.

Today i did the remainder to follow the code-style. All ready now.

**Comment by dcrossleyau** [comment]
Youch. We had discussed offline how the config newline things might affect scripts. I should have looked more deeply.

With the YAML reformat, i had neglected to verify that the orginal had consistent indent. It is good that it will be so now.

Sorry to cause you work.

**Comment by wafschneider** [comment]
Is this ready to merge? @funkymalc, was there something that needed to happen with the Jenkinsfile?

**Pull request merged**
